---
abstract: 'Interface to SAB TV Programmes Schedules.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTML::TokeParser::Simple: 3.15
  HTTP::Request: 1.40
  LWP::UserAgent: 2.33
  Moose: 2.0006
  Moose::Util::TypeConstraints: 2.0006
  MooseX::Params::Validate: 0.16
  Readonly: 0
  Test::More: 0
  Time::localtime: 1.02
  namespace::clean: 0.20
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TV-ProgrammesSchedules-SAB
provides:
  TV::ProgrammesSchedules::SAB:
    file: lib/TV/ProgrammesSchedules/SAB.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
